### ISSUE TITLE
Create a custom domain?

### ISSUE THREAD

**Issue by jessesquires** [techworkersco/techworkersco.github.io#18]
We briefly discussed this in our last meeting.

### Possible options:

1. totally new domain (I think `twc.news` would be cool)
2. subdomain, probably `news.techworkerscoalition.org` is best

### Potential concerns

- A single person "owns" this, whereas the `.github.io` domain is "unowned"
- Someone needs to pay for this. We can all contribute, but we need a single "credit card holder" or someone to actually register the domain. (However, I'm not sure how this works for subdomains?)

### Docs

- https://help.github.com/en/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site
- https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain

### Tasks

- [x] Get the domain
- [x] Create a `CNAME` file
- [ ] Update `_config.yml`
- [ ] Anything else?

**Comment by jessesquires** [comment]
I don't have a strong opinion on this.

I don't really know how the subdomain thing works. I don't know who currently owns `techworkerscoalition.org`.

cc @kidmillions Can you offer any ideas or help here?

**Comment by shushugah** [comment]
@kidmillions is the domain owner of `techworkerscoalition.org`.

I would prefer `news.techworkerscoalition.org` for for 2 reasons, one is Page Ranking, the other is...it's clearer who this website/project is affiliated with without doing any digging.

I plan on moving `techworkersberlin.com` to `berlin.techworkerscoalition.org`, but you can see a sample blog interface here `https://techworkersberlin.com/news`

I'd be interested/happy to help with the newsletter in general :)

**Comment by stationaery** [comment]
Those are good reasons for the longer URL. That’s our default for now.
However, I think that twc.news is easier for typing/sharing. Getting a view
of all properties and traffic patterns might help us decide.

As for contributing/collaborating... Wunderbar! Berlin seems to have a lot
going for it, and much to teach. We plan to have materials and also a
meeting for new contributors and collaborators next month.

**Comment by jessesquires** [comment]
Using `news.techworkerscoalition.org` for the canonical url sounds best.

Then we could have `twc.news` as an alias.

**Comment by jessesquires** [comment]
custom domain done in b8d13eda6a0cc6fa14967b5ca3b3d277a42c508d thanks to @kidmillions 🙌

**Comment by jessesquires** [comment]
alright, finished up by updating our `_config` in 1507536c9efffd054b6682a2531f19dffc53901e.

we should be good to go here.

@stationaery let's revisit `twc.news` as a shorter alias in the future

**Comment by anaulin** [comment]
It probably doesn't matter much, but this repo is still named `techworkersco.github.io`. Might be nice to rename it to "news" or "newsletter" or "news-bayarea" or something else that is descriptive and doesn't have a misleading URL.

**Comment by jessesquires** [comment]
Unfortunately, the current name is required for GH-pages to work.

---

Well, sort of. It is possible to have another name for this repo, but it makes the jekyll setup and gh-pages hosting much more complex.

The difference is between user/organization sites vs project sites. Project sites are hosted at `/PROJECT_NAME` instead of `/` so things get... weird.

For example:

- `techworkersco.github.io` is an organization-level site.
- Renaming would give us a project site at `techworkersco.github.io/newsletter`

I initially started down that route (the repo was named `newsletter`), but I ran into enough problems that it didn't seem worth it. (Because then things like `/css/style.css` are no longer correct.)

---

Willing to revisit though if someone wants to attempt this.

**Comment by anaulin** [comment]
Ah, got it. I think you already explained this but I forgot, @jessesquires , sorry for bringing it up again. I don't think it's worth much hassle to rename the repo.

**Comment by shushugah** [comment]
Hosting it on Netlify would be a solution around this, and you would get many benefits of Netlify, such as previews during pull requests, the ability to run jekyll plugins outside of `--safe mode` (for example no github approved jekyll plugin exists for `i18n`

By default inside `_config` the `baseUrl` is `/` but you'd need to change it to the repository name IF you were using githubpages as your domain. Since `https://news.techworkerscoalition.org/` is the root domain, this is not needed anymore.

**Comment by shushugah** [comment]
Unfortunately, there's also another bug with github pages. If I created a second githubpage project called `about` which would be available at `techworkersco.github.io/about` it would also be available at `news.techworkerscoalition.org/about`, which could conflict with an actual sub resource with same name

**Comment by jessesquires** [comment]
> Hosting it on Netlify would be a solution around this...

I don't know much about Netlify. But we're aiming for the simplest solution at the moment, and also the "free-est" solution. I'm not 100% sure how to interpret Netlify's [pricing](https://www.netlify.com/pricing/), but 1 team member for a free account sounds too limited and the "pro" package is expensive, considering we have 5 core members on this project and the alternative (what we currently have) is free.

>  the ability to run jekyll plugins outside of --safe mode (for example no github approved jekyll plugin exists for `i18n`) ...

I don't think we have any interest in extra plugins right now. And, we certainly don't have capacity for `i18n` at the moment.

 > By default inside `_config` the `baseUrl` is `/` but you'd need to change it to the repository name IF you were using githubpages as your domain. Since `https://news.techworkerscoalition.org/` is the root domain, this is not needed anymore. 

Ahhh, interesting. So we could safely rename the repo?

> Unfortunately, there's also another bug with github pages....

Ha 😅 I never thought about that. Good to keep this in mind, but I would wait until this is actually a problem instead of investing in something now.

---

Thanks @shushugah for bringing all this up! I think we should definitely keep it in mind and consider these changes if/when the project grows.
