### ISSUE TITLE
Create publishing checklist doc

### ISSUE THREAD

**Issue by jessesquires** [techworkersco/techworkersco.github.io#54]
Per our discussion during the May 5 meeting.

@stationaery I think you volunteered to do this? 

#### Meeting Notes

> Schedule before Friday:
>
> - Final edits by Thursday at 2pm, proofreading and QA by 6pm Thursday
> - Issue theme picked and draft started by 5pm Monday
> - Issue lead and co-lead decided by 5pm Friday, considering various appealing themes

**Comment by stationaery** [comment]
Yep! Will create a checklist for us by Monday

**Comment by stationaery** [comment]
Draft publishing checklist:
- [ ] Collective updates queue of issue contributors by 2pm Pacific Friday
- [ ] Collective decides on issue lead and co-lead by 5pm Friday
- [ ] Lead and co-lead select theme and start draft by 5pm Monday
- [ ] Lead and co-lead complete and share final draft by 2pm Thursday
- [ ] Collective proofreads and finishes QA by 6pm Thursday
- [ ] Collective pushes issue by 6pm Thursday (or 9am Friday at the latest)
- [ ] Automagic distribution via email and social media at 10am Friday

Anything unclear, missing, or unreasonable in here?

**Comment by jessesquires** [comment]
Opened a PR at #63.

Going to close this and we can move the discussion there.
